eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/
#101.132.38.94
server:
  port: 8765
spring:
  application:
    name: service-biz